package localrp

import (
	"crypto/rand"
	"fmt"
	"strings"
	"time"
)

// BeginLocalLogin (design doc: "SDK API Shape", "Flow" steps 4-6). Mirrors
// sdks/local-rp/rust/src/begin.rs.
//
// Pure/offline: no network access happens here. It generates a fresh
// nonce/state, builds and signs a LocalRpLoginRequest around the identity's
// already-signed descriptor, and returns a redirect URL plus the
// pending-login state the app must persist and treat as single-use.

// DefaultRequestedClaims are the default requested claims when the caller
// doesn't specify any (design doc, "Default Claim Set"): a usable "identity"
// out of the box with zero claim configuration.
var DefaultRequestedClaims = []string{"display_name", "email", "handle"}

// DefaultRequiredClaims are the default required claims (design doc,
// "Default Claim Set").
var DefaultRequiredClaims = []string{"handle"}

// DefaultLoginRequestLifetime is the default login-request lifetime:
// short-lived, matching the callback's own short default lifetime (design
// doc: "callback lifetime is short, default 5 minutes").
const DefaultLoginRequestLifetime = 5 * time.Minute

// BeginLocalLoginConfig is the input to BeginLocalLogin. Big-config, single
// struct.
type BeginLocalLoginConfig struct {
	// KeyMaterial is the identity generated by GenerateLocalRpIdentity. Its
	// already-signed descriptor is reused as-is in the login request.
	KeyMaterial *LocalRpKeyMaterial
	// CallbackURL is where the IDP should redirect the browser back to
	// after login. Must be http:// or https:// (design doc, "Callback URL
	// Rules") — the IDP enforces this authoritatively, but this SDK checks
	// it too so a misconfigured app fails fast.
	CallbackURL string
	// UserDomain is the LinkKeys domain the user selected/entered.
	UserDomain string
	// RequestedClaims are the optional requested claims. Defaults to
	// DefaultRequestedClaims when nil.
	RequestedClaims []string
	// RequiredClaims are the required claims — login fails at the IDP if
	// the user can't/won't satisfy these. Defaults to DefaultRequiredClaims
	// when nil.
	RequiredClaims []string
	// RequestLifetime is the login-request lifetime from Now. Defaults to
	// DefaultLoginRequestLifetime when zero.
	RequestLifetime time.Duration
	Now             time.Time
}

// LocalLoginRedirect is the redirect URL the app should send the user's
// browser to. The SDK never performs the redirect itself (design doc:
// "Browser-only Flow" — opening a browser is a UX decision outside the
// LinkKeys SDK).
type LocalLoginRedirect struct {
	RedirectURL string
}

// PendingLogin is the state BeginLocalLogin returns for the app to persist
// (e.g. in a server-side session tied to the browser) and pass unchanged to
// CompleteLocalLogin. Single-use: the design doc requires the app discard it
// after one completion attempt — this package cannot enforce that itself
// (it owns no storage), so replay protection at the app boundary is the
// app's responsibility. JSON-tagged so the app can serialize it into
// whatever session store it already uses.
type PendingLogin struct {
	Nonce       []byte `json:"nonce"`
	State       []byte `json:"state"`
	UserDomain  string `json:"user_domain"`
	CallbackURL string `json:"callback_url"`
	// RequiredClaims are the claim types this login demanded (the same list
	// sent to the IDP, defaulted the same way — see BeginLocalLoginConfig).
	// CompleteLocalLogin enforces that every one of these appears among the
	// claims returned by ticket redemption that pass full signature
	// verification; without retaining this here, that enforcement would be
	// impossible (the redemption response itself carries no notion of what
	// was required).
	RequiredClaims []string `json:"required_claims"`
}

func validateCallbackScheme(url string) error {
	if strings.HasPrefix(url, "http://") || strings.HasPrefix(url, "https://") {
		return nil
	}
	return &InvalidInputError{Detail: fmt.Sprintf("callback_url must be http:// or https://, got: %q", url)}
}

// BeginLocalLogin implements `begin_local_login(config) ->
// (LocalLoginRedirect, PendingLogin)` (design doc, "SDK API Shape").
// Generates a fresh nonce/state, builds and signs a LocalRpLoginRequest
// (envelope + linkkeys-local-rp-login-request context) around the
// identity's descriptor, and returns the full redirect URL for the user's
// LinkKeys domain plus the pending-login state.
func BeginLocalLogin(config BeginLocalLoginConfig) (*LocalLoginRedirect, *PendingLogin, error) {
	if err := validateCallbackScheme(config.CallbackURL); err != nil {
		return nil, nil, err
	}
	if strings.TrimSpace(config.UserDomain) == "" {
		return nil, nil, &InvalidInputError{Detail: "user_domain must not be empty"}
	}

	nonce := make([]byte, 32)
	if _, err := rand.Read(nonce); err != nil {
		return nil, nil, err
	}
	state := make([]byte, 32)
	if _, err := rand.Read(state); err != nil {
		return nil, nil, err
	}

	requestedClaims := config.RequestedClaims
	if requestedClaims == nil {
		requestedClaims = append([]string{}, DefaultRequestedClaims...)
	}
	requiredClaims := config.RequiredClaims
	if requiredClaims == nil {
		requiredClaims = append([]string{}, DefaultRequiredClaims...)
	}

	lifetime := config.RequestLifetime
	if lifetime == 0 {
		lifetime = DefaultLoginRequestLifetime
	}
	issuedAt := config.Now.UTC().Format(time.RFC3339Nano)
	expiresAt := config.Now.Add(lifetime).UTC().Format(time.RFC3339Nano)

	request := BuildLocalRpLoginRequest(config.KeyMaterial.Descriptor, config.CallbackURL, nonce, state, requestedClaims, requiredClaims, issuedAt, expiresAt)
	signed := SignLocalRpLoginRequest(request, config.KeyMaterial.SigningPrivateKey)

	encoded := SignedLocalRpLoginRequestToURLParam(signed)

	// Wire Precision: "Begin route: GET /auth/local-rp?signed_request=<...>"
	// — mirrors the existing GET /auth/authorize?signed_request=... shape.
	redirectURL := fmt.Sprintf("https://%s/auth/local-rp?signed_request=%s", config.UserDomain, encoded)

	return &LocalLoginRedirect{RedirectURL: redirectURL}, &PendingLogin{
			Nonce:          nonce,
			State:          state,
			UserDomain:     config.UserDomain,
			CallbackURL:    config.CallbackURL,
			RequiredClaims: requiredClaims,
		},
		nil
}
