image:
  repository: 10.16.0.1:5000/public/catalystcommunity/linkkeys

server:
  domainName: "linkkeys.todandlorna.com"
  publicPort: "443"
  disableTls: "true"
  disableTcpTls: "true"

database:
  backend: postgres

postgresql:
  enabled: true
  teamId: linkkeys
  database: linkkeys
  user: linkkeys
  instances: 1
  storage:
    size: 1Gi

gateway:
  httpRoute:
    enabled: true
    parentGateway: contour
    parentNamespace: projectcontour
    parentSection: http
    hostnames:
      - linkkeys.todandlorna.com
