// `beginLocalLogin` (design doc: "SDK API Shape", "Flow" steps 4-6). Mirrors
// `sdks/local-rp/go/begin.go`.
//
// It generates a fresh nonce/state, builds and signs a `LocalRpLoginRequest`
// around the identity's already-signed descriptor, and returns a redirect
// URL plus the pending-login state the app must persist and treat as
// single-use.
//
// The signing work is pure/offline. The one network touch is a DNS TXT
// lookup of `_linkkeys_apis.<userDomain>` to discover the browser-facing
// HTTPS endpoint (the identity domain is a trust domain, not necessarily
// the host serving the login routes). The resolver is injectable via
// `BeginLocalLoginConfig.dns`; on any discovery failure the redirect falls
// back to `https://<userDomain>`.

import { BROWSER_ROUTE_LOCAL_RP, resolveBrowserEndpoint } from "./browser.ts";
import { randomBytes } from "./crypto.ts";
import { defaultDnsResolver } from "./defaults.ts";
import type { DnsResolver } from "./dns.ts";
import { signedLocalRpLoginRequestToUrlParam } from "./encoding.ts";
import { InvalidInputError, type LocalRpKeyMaterial } from "./identity.ts";
import { buildLocalRpLoginRequest, signLocalRpLoginRequest } from "./localRp.ts";

/** Default requested claims when the caller doesn't specify any (design doc, "Default Claim Set"). */
export const DEFAULT_REQUESTED_CLAIMS = ["display_name", "email", "handle"] as const;
/** Default required claims (design doc, "Default Claim Set"). */
export const DEFAULT_REQUIRED_CLAIMS = ["handle"] as const;
/** Default login-request lifetime: short-lived, matching the callback's own short default lifetime. */
export const DEFAULT_LOGIN_REQUEST_LIFETIME_MS = 5 * 60 * 1000;

/** Input to `beginLocalLogin`. Big-config, single object. */
export interface BeginLocalLoginConfig {
  /** The identity generated by `generateLocalRpIdentity`. Its already-signed descriptor is reused as-is. */
  keyMaterial: LocalRpKeyMaterial;
  /** Where the IDP should redirect the browser back to after login. Must be `http://` or `https://`. */
  callbackUrl: string;
  /** The LinkKeys login or domain. A full login adds a username hint. */
  userDomain: string;
  /** Requested (optional) claims. Defaults to `DEFAULT_REQUESTED_CLAIMS` when omitted. */
  requestedClaims?: readonly string[];
  /** Required claims. Defaults to `DEFAULT_REQUIRED_CLAIMS` when omitted. */
  requiredClaims?: readonly string[];
  /** Login-request lifetime from `now`, in milliseconds. Defaults to `DEFAULT_LOGIN_REQUEST_LIFETIME_MS`. */
  requestLifetimeMs?: number;
  now: Date;
  /**
   * The DNS TXT lookup seam for browser endpoint discovery
   * (`_linkkeys_apis.<userDomain>`, its `https=` endpoint). Defaults to
   * `defaultDnsResolver()` when omitted, same as `CompleteLocalLoginConfig.dns`.
   */
  dns?: DnsResolver;
}

/** The redirect URL the app should send the user's browser to. This SDK never performs the redirect itself. */
export interface LocalLoginRedirect {
  redirectUrl: string;
}

/**
 * The state `beginLocalLogin` returns for the app to persist (e.g. in a
 * server-side session tied to the browser) and pass unchanged to
 * `completeLocalLogin`. Plain, JSON-serializable data. **Single-use**: the
 * app must discard it after one completion attempt — this SDK owns no
 * storage and cannot enforce that itself.
 */
export interface PendingLogin {
  nonceHex: string;
  stateHex: string;
  userDomain: string;
  callbackUrl: string;
  /**
   * The required-claims list this login actually requested (post-default —
   * `DEFAULT_REQUIRED_CLAIMS` when the caller didn't override it).
   * `completeLocalLogin` enforces that every one of these claim types is
   * present among the verified claims the IDP returns; persisted here so
   * that enforcement is against what THIS login demanded, not whatever the
   * IDP later claims was required.
   */
  requiredClaims: string[];
}

export function validateCallbackScheme(url: string): void {
  if (!url.startsWith("http://") && !url.startsWith("https://")) {
    throw new InvalidInputError(`callbackUrl must be http:// or https://, got: ${JSON.stringify(url)}`);
  }
}

function toHex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("hex");
}

export function parseIdentityInput(value: string): { username?: string; domain: string } {
  const input = value.trim();
  if (!/^[\x00-\x7F]+$/.test(input) || (input.match(/@/g)?.length ?? 0) > 1) {
    throw new InvalidInputError("identity must be a username@domain or a domain");
  }
  const separator = input.indexOf("@");
  const username = separator >= 0 ? input.slice(0, separator) : undefined;
  const domain = separator >= 0 ? input.slice(separator + 1) : input;
  if (username !== undefined && !/^(?!\.)(?!.*\.\.)[A-Za-z0-9!#$%&'*+\-/=?^_`{|}~.]{1,64}(?<!\.)$/.test(username)) {
    throw new InvalidInputError("identity must be a username@domain or a domain");
  }
  const domainMatch = /^([^:]+)(?::([0-9]+))?$/.exec(domain);
  const host = domainMatch?.[1] ?? "";
  const port = domainMatch?.[2];
  const labels = host.split(".");
  const validHost = host.length <= 253 && (host.includes(".") || port !== undefined) && labels.every(
    (label) => label.length >= 1 && label.length <= 63 && /^(?!-)[A-Za-z0-9-]+(?<!-)$/.test(label),
  );
  const portNumber = port === undefined ? undefined : Number(port);
  if (!validHost || domain.length > 259 || (portNumber !== undefined && (!Number.isInteger(portNumber) || portNumber < 1 || portNumber > 65535))) {
    throw new InvalidInputError("identity must be a username@domain or a domain");
  }
  return { username, domain: domain.toLowerCase() };
}

/**
 * `begin_local_login(config) -> (LocalLoginRedirect, PendingLogin)` (design
 * doc, "SDK API Shape"). Generates a fresh nonce/state, builds and signs a
 * `LocalRpLoginRequest`, and returns the full redirect URL for the user's
 * LinkKeys domain plus the pending-login state.
 *
 * Async because the redirect host comes from a `_linkkeys_apis` DNS TXT
 * lookup (see this module's header). The lookup never fails the call: on
 * any discovery failure the redirect falls back to `https://<userDomain>`.
 */
export async function beginLocalLogin(config: BeginLocalLoginConfig): Promise<{
  redirect: LocalLoginRedirect;
  pending: PendingLogin;
}> {
  validateCallbackScheme(config.callbackUrl);
  const identity = parseIdentityInput(config.userDomain);

  const nonce = randomBytes(32);
  const state = randomBytes(32);

  const requestedClaims = config.requestedClaims ?? DEFAULT_REQUESTED_CLAIMS;
  const requiredClaims = config.requiredClaims ?? DEFAULT_REQUIRED_CLAIMS;
  const lifetimeMs = config.requestLifetimeMs ?? DEFAULT_LOGIN_REQUEST_LIFETIME_MS;
  const issuedAt = config.now.toISOString();
  const expiresAt = new Date(config.now.getTime() + lifetimeMs).toISOString();

  const request = buildLocalRpLoginRequest(
    config.keyMaterial.descriptor,
    config.callbackUrl,
    nonce,
    state,
    requestedClaims,
    requiredClaims,
    issuedAt,
    expiresAt,
  );
  const signed = signLocalRpLoginRequest(request, config.keyMaterial.signingPrivateKey);
  const encoded = signedLocalRpLoginRequestToUrlParam(signed);

  // Wire Precision: "Begin route: GET /auth/local-rp?signed_request=<...>"
  // — mirrors the existing GET /auth/authorize?signed_request=... shape.
  // The host comes from `_linkkeys_apis.<userDomain>` discovery (with a
  // fallback to the identity domain itself); `pending.userDomain` stays the
  // identity domain — verification is bound to it, never to the discovered
  // service host.
  const dns = config.dns ?? defaultDnsResolver();
  const redirect = new URL(await resolveBrowserEndpoint(dns, identity.domain, BROWSER_ROUTE_LOCAL_RP, encoded));
  if (identity.username !== undefined) redirect.searchParams.set("username", identity.username);
  const redirectUrl = redirect.toString();

  return {
    redirect: { redirectUrl },
    pending: {
      nonceHex: toHex(nonce),
      stateHex: toHex(state),
      userDomain: identity.domain,
      callbackUrl: config.callbackUrl,
      requiredClaims: [...requiredClaims],
    },
  };
}
