// `beginLocalLogin` (design doc: "SDK API Shape", "Flow" steps 4-6). Mirrors
// `sdks/local-rp/rust/src/begin.rs`.
//
// Pure/offline: no network access happens here. It generates a fresh
// nonce/state, builds and signs a `LocalRpLoginRequest` around the
// identity's already-signed descriptor, and returns a redirect URL plus the
// pending-login state the app must persist and treat as single-use.

import { randomBytes } from "./crypto.ts";
import { signedLocalRpLoginRequestToUrlParam } from "./encoding.ts";
import { InvalidInputError, type LocalRpKeyMaterial } from "./identity.ts";
import { buildLocalRpLoginRequest, signLocalRpLoginRequest } from "./localRp.ts";

/** Default requested claims when the caller doesn't specify any (design doc, "Default Claim Set"). */
export const DEFAULT_REQUESTED_CLAIMS = ["display_name", "email", "handle"] as const;
/** Default required claims (design doc, "Default Claim Set"). */
export const DEFAULT_REQUIRED_CLAIMS = ["handle"] as const;
/** Default login-request lifetime: short-lived, matching the callback's own short default lifetime. */
export const DEFAULT_LOGIN_REQUEST_LIFETIME_MS = 5 * 60 * 1000;

/** Input to `beginLocalLogin`. Big-config, single object. */
export interface BeginLocalLoginConfig {
  /** The identity generated by `generateLocalRpIdentity`. Its already-signed descriptor is reused as-is. */
  keyMaterial: LocalRpKeyMaterial;
  /** Where the IDP should redirect the browser back to after login. Must be `http://` or `https://`. */
  callbackUrl: string;
  /** The LinkKeys domain the user selected/entered. */
  userDomain: string;
  /** Requested (optional) claims. Defaults to `DEFAULT_REQUESTED_CLAIMS` when omitted. */
  requestedClaims?: readonly string[];
  /** Required claims. Defaults to `DEFAULT_REQUIRED_CLAIMS` when omitted. */
  requiredClaims?: readonly string[];
  /** Login-request lifetime from `now`, in milliseconds. Defaults to `DEFAULT_LOGIN_REQUEST_LIFETIME_MS`. */
  requestLifetimeMs?: number;
  now: Date;
}

/** The redirect URL the app should send the user's browser to. This SDK never performs the redirect itself. */
export interface LocalLoginRedirect {
  redirectUrl: string;
}

/**
 * The state `beginLocalLogin` returns for the app to persist (e.g. in a
 * server-side session tied to the browser) and pass unchanged to
 * `completeLocalLogin`. Plain, JSON-serializable data. **Single-use**: the
 * app must discard it after one completion attempt — this SDK owns no
 * storage and cannot enforce that itself.
 */
export interface PendingLogin {
  nonceHex: string;
  stateHex: string;
  userDomain: string;
  callbackUrl: string;
  /**
   * The required-claims list this login actually requested (post-default —
   * `DEFAULT_REQUIRED_CLAIMS` when the caller didn't override it).
   * `completeLocalLogin` enforces that every one of these claim types is
   * present among the verified claims the IDP returns; persisted here so
   * that enforcement is against what THIS login demanded, not whatever the
   * IDP later claims was required.
   */
  requiredClaims: string[];
}

function validateCallbackScheme(url: string): void {
  if (!url.startsWith("http://") && !url.startsWith("https://")) {
    throw new InvalidInputError(`callbackUrl must be http:// or https://, got: ${JSON.stringify(url)}`);
  }
}

function toHex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("hex");
}

/**
 * `begin_local_login(config) -> (LocalLoginRedirect, PendingLogin)` (design
 * doc, "SDK API Shape"). Generates a fresh nonce/state, builds and signs a
 * `LocalRpLoginRequest`, and returns the full redirect URL for the user's
 * LinkKeys domain plus the pending-login state.
 */
export function beginLocalLogin(config: BeginLocalLoginConfig): {
  redirect: LocalLoginRedirect;
  pending: PendingLogin;
} {
  validateCallbackScheme(config.callbackUrl);
  if (config.userDomain.trim().length === 0) {
    throw new InvalidInputError("userDomain must not be empty");
  }

  const nonce = randomBytes(32);
  const state = randomBytes(32);

  const requestedClaims = config.requestedClaims ?? DEFAULT_REQUESTED_CLAIMS;
  const requiredClaims = config.requiredClaims ?? DEFAULT_REQUIRED_CLAIMS;
  const lifetimeMs = config.requestLifetimeMs ?? DEFAULT_LOGIN_REQUEST_LIFETIME_MS;
  const issuedAt = config.now.toISOString();
  const expiresAt = new Date(config.now.getTime() + lifetimeMs).toISOString();

  const request = buildLocalRpLoginRequest(
    config.keyMaterial.descriptor,
    config.callbackUrl,
    nonce,
    state,
    requestedClaims,
    requiredClaims,
    issuedAt,
    expiresAt,
  );
  const signed = signLocalRpLoginRequest(request, config.keyMaterial.signingPrivateKey);
  const encoded = signedLocalRpLoginRequestToUrlParam(signed);

  // Wire Precision: "Begin route: GET /auth/local-rp?signed_request=<...>".
  const redirectUrl = `https://${config.userDomain}/auth/local-rp?signed_request=${encoded}`;

  return {
    redirect: { redirectUrl },
    pending: {
      nonceHex: toHex(nonce),
      stateHex: toHex(state),
      userDomain: config.userDomain,
      callbackUrl: config.callbackUrl,
      requiredClaims: [...requiredClaims],
    },
  };
}
