//! `begin_local_login` (design doc: "SDK API Shape", "Flow" steps 4-6).
//!
//! Pure/offline: no network access happens here. It generates a fresh
//! nonce/state, builds and signs a `LocalRpLoginRequest` around the
//! identity's already-signed descriptor, and returns a redirect URL plus the
//! pending-login state the app must persist and treat as single-use.

use crate::identity::LocalRpKeyMaterial;
use crate::Error;
use chrono::{DateTime, Duration, Utc};
use liblinkkeys::{encoding, local_rp};
use serde::{Deserialize, Serialize};

/// Default requested claims when the caller doesn't specify any (design doc,
/// "Default Claim Set"): a usable "identity" out of the box with zero claim
/// configuration.
pub const DEFAULT_REQUESTED_CLAIMS: &[&str] = &["display_name", "email", "handle"];
/// Default required claims (design doc, "Default Claim Set").
pub const DEFAULT_REQUIRED_CLAIMS: &[&str] = &["handle"];
/// Default login-request lifetime: short-lived, matching the callback's own
/// short default lifetime (design doc: "callback lifetime is short, default
/// 5 minutes").
pub const DEFAULT_LOGIN_REQUEST_LIFETIME: Duration = Duration::minutes(5);

/// Input to [`begin_local_login`]. Big-config, single struct.
#[derive(Debug, Clone)]
pub struct BeginLocalLoginConfig<'a> {
    /// The identity generated by [`crate::generate_local_rp_identity`]. Its
    /// already-signed descriptor is reused as-is in the login request — see
    /// [`LocalRpKeyMaterial`]'s docs for why this SDK doesn't re-sign a fresh
    /// descriptor per login.
    pub key_material: &'a LocalRpKeyMaterial,
    /// Where the IDP should redirect the browser back to after login. Must
    /// be `http://` or `https://` (design doc, "Callback URL Rules") — the
    /// IDP enforces this authoritatively, but this SDK checks it too so a
    /// misconfigured app fails fast instead of burning a round trip to
    /// discover it from the IDP's rejection page.
    pub callback_url: String,
    /// The LinkKeys domain the user selected/entered.
    pub user_domain: String,
    /// Requested (optional) claims. Defaults to [`DEFAULT_REQUESTED_CLAIMS`]
    /// when `None`.
    pub requested_claims: Option<Vec<String>>,
    /// Required claims — login fails at the IDP if the user can't/won't
    /// satisfy these. Defaults to [`DEFAULT_REQUIRED_CLAIMS`] when `None`.
    pub required_claims: Option<Vec<String>>,
    /// Login-request lifetime from `now`. Defaults to
    /// [`DEFAULT_LOGIN_REQUEST_LIFETIME`] when `None`.
    pub request_lifetime: Option<Duration>,
    pub now: DateTime<Utc>,
}

impl<'a> BeginLocalLoginConfig<'a> {
    /// Convenience constructor for the common case (default claims and
    /// lifetime).
    pub fn new(
        key_material: &'a LocalRpKeyMaterial,
        callback_url: impl Into<String>,
        user_domain: impl Into<String>,
        now: DateTime<Utc>,
    ) -> Self {
        Self {
            key_material,
            callback_url: callback_url.into(),
            user_domain: user_domain.into(),
            requested_claims: None,
            required_claims: None,
            request_lifetime: None,
            now,
        }
    }
}

/// The redirect URL the app should send the user's browser to. The SDK never
/// performs the redirect itself (design doc: "Browser-only Flow" — "Opening
/// a browser is a UX decision outside the LinkKeys SDK").
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalLoginRedirect {
    pub redirect_url: String,
}

/// The state `begin_local_login` returns for the app to persist (e.g. in a
/// server-side session tied to the browser) and pass unchanged to
/// `complete_local_login`. **Single-use**: the design doc requires the app
/// discard it after one completion attempt — this crate cannot enforce that
/// itself (it owns no storage), so replay protection at the app boundary is
/// the app's responsibility.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PendingLogin {
    pub nonce: Vec<u8>,
    pub state: Vec<u8>,
    pub user_domain: String,
    pub callback_url: String,
    /// The claim types this login required (design doc, "Default Claim
    /// Set" / SEC checklist: "the app-declared required claims are
    /// actually enforced"). `complete_local_login` re-checks this set
    /// against the redemption's verified claims — it must round-trip
    /// through whatever storage the app persists `PendingLogin` in, so a
    /// login that began requiring e.g. `handle` can't complete without it
    /// just because the requirement was forgotten between `begin` and
    /// `complete`.
    pub required_claims: Vec<String>,
}

fn validate_callback_scheme(url: &str) -> Result<(), Error> {
    if url.starts_with("http://") || url.starts_with("https://") {
        Ok(())
    } else {
        Err(Error::InvalidInput(format!(
            "callback_url must be http:// or https://, got: {url:?}"
        )))
    }
}

/// `begin_local_login(config) -> (LocalLoginRedirect, PendingLogin)` (design
/// doc, "SDK API Shape"). Generates a fresh nonce/state, builds and signs a
/// `LocalRpLoginRequest` (envelope + `linkkeys-local-rp-login-request`
/// context) around the identity's descriptor, and returns the full redirect
/// URL for the user's LinkKeys domain plus the pending-login state.
pub fn begin_local_login(
    config: BeginLocalLoginConfig<'_>,
) -> Result<(LocalLoginRedirect, PendingLogin), Error> {
    validate_callback_scheme(&config.callback_url)?;
    if config.user_domain.trim().is_empty() {
        return Err(Error::InvalidInput(
            "user_domain must not be empty".to_string(),
        ));
    }

    let nonce: [u8; 32] = rand::random();
    let state: [u8; 32] = rand::random();

    let requested_claims = config.requested_claims.unwrap_or_else(|| {
        DEFAULT_REQUESTED_CLAIMS
            .iter()
            .map(|s| s.to_string())
            .collect()
    });
    let required_claims = config.required_claims.unwrap_or_else(|| {
        DEFAULT_REQUIRED_CLAIMS
            .iter()
            .map(|s| s.to_string())
            .collect()
    });
    let lifetime = config
        .request_lifetime
        .unwrap_or(DEFAULT_LOGIN_REQUEST_LIFETIME);
    let issued_at = config.now.to_rfc3339();
    let expires_at = (config.now + lifetime).to_rfc3339();

    // Cloned before the move below: `PendingLogin` must retain the same
    // required-claim set so `complete_local_login` can enforce it later.
    let pending_required_claims = required_claims.clone();

    let request = local_rp::build_local_rp_login_request(
        config.key_material.descriptor.clone(),
        &config.callback_url,
        nonce.to_vec(),
        state.to_vec(),
        requested_claims,
        required_claims,
        &issued_at,
        &expires_at,
    );
    let signed =
        local_rp::sign_local_rp_login_request(&request, &config.key_material.signing_private_key)
            .map_err(Error::from)?;

    let encoded = encoding::signed_local_rp_login_request_to_url_param(&signed)
        .map_err(|e| Error::Decode(e.to_string()))?;

    // Wire Precision: "Begin route: GET /auth/local-rp?signed_request=<...>"
    // — mirrors the existing GET /auth/authorize?signed_request=... shape.
    let redirect_url = format!(
        "https://{}/auth/local-rp?signed_request={}",
        config.user_domain, encoded
    );

    Ok((
        LocalLoginRedirect { redirect_url },
        PendingLogin {
            nonce: nonce.to_vec(),
            state: state.to_vec(),
            user_domain: config.user_domain,
            callback_url: config.callback_url,
            required_claims: pending_required_claims,
        },
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::identity::{generate_local_rp_identity, GenerateLocalRpIdentityConfig};

    fn material() -> LocalRpKeyMaterial {
        generate_local_rp_identity(GenerateLocalRpIdentityConfig::new("Test App", Utc::now()))
            .unwrap()
    }

    #[test]
    fn begin_defaults_claims_and_produces_pending_state() {
        let m = material();
        let (redirect, pending) = begin_local_login(BeginLocalLoginConfig::new(
            &m,
            "http://localhost:8080/callback",
            "example.com",
            Utc::now(),
        ))
        .unwrap();

        assert!(redirect
            .redirect_url
            .starts_with("https://example.com/auth/local-rp?signed_request="));
        assert_eq!(pending.user_domain, "example.com");
        assert_eq!(pending.callback_url, "http://localhost:8080/callback");
        assert_eq!(pending.nonce.len(), 32);
        assert_eq!(pending.state.len(), 32);
        assert_eq!(
            pending.required_claims,
            DEFAULT_REQUIRED_CLAIMS
                .iter()
                .map(|s| s.to_string())
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn begin_retains_caller_supplied_required_claims_in_pending_state() {
        let m = material();
        let mut config =
            BeginLocalLoginConfig::new(&m, "http://localhost/callback", "example.com", Utc::now());
        config.required_claims = Some(vec!["email".to_string(), "handle".to_string()]);
        let (_, pending) = begin_local_login(config).unwrap();
        assert_eq!(
            pending.required_claims,
            vec!["email".to_string(), "handle".to_string()]
        );
    }

    #[test]
    fn begin_rejects_non_http_callback_scheme() {
        let m = material();
        let result = begin_local_login(BeginLocalLoginConfig::new(
            &m,
            "myapp://callback",
            "example.com",
            Utc::now(),
        ));
        assert!(matches!(result, Err(Error::InvalidInput(_))));
    }

    #[test]
    fn begin_two_calls_never_reuse_nonce_or_state() {
        let m = material();
        let (_, p1) = begin_local_login(BeginLocalLoginConfig::new(
            &m,
            "http://localhost/callback",
            "example.com",
            Utc::now(),
        ))
        .unwrap();
        let (_, p2) = begin_local_login(BeginLocalLoginConfig::new(
            &m,
            "http://localhost/callback",
            "example.com",
            Utc::now(),
        ))
        .unwrap();
        assert_ne!(p1.nonce, p2.nonce);
        assert_ne!(p1.state, p2.state);
    }

    #[test]
    fn pending_login_is_serializable() {
        let m = material();
        let (_, pending) = begin_local_login(BeginLocalLoginConfig::new(
            &m,
            "http://localhost/callback",
            "example.com",
            Utc::now(),
        ))
        .unwrap();
        let json = serde_json::to_string(&pending).unwrap();
        let round_tripped: PendingLogin = serde_json::from_str(&json).unwrap();
        assert_eq!(round_tripped, pending);
    }
}
