//! `begin_local_login` (design doc: "SDK API Shape", "Flow" steps 4-6).
//!
//! It generates a fresh nonce/state, builds and signs a `LocalRpLoginRequest`
//! around the identity's already-signed descriptor, and returns a redirect
//! URL plus the pending-login state the app must persist and treat as
//! single-use.
//!
//! The signing work is pure/offline. The one network touch is a DNS TXT
//! lookup of `_linkkeys_apis.<user_domain>` to discover the browser-facing
//! HTTPS endpoint (the identity domain is a trust domain, not necessarily
//! the host serving the login routes — see [`crate::browser`]). The resolver
//! is injectable via [`BeginLocalLoginConfig::dns`]; on any discovery
//! failure the redirect falls back to `https://<user_domain>`.

use crate::browser::{resolve_browser_endpoint, BROWSER_ROUTE_LOCAL_RP};
use crate::dns::DnsResolver;
use crate::identity::LocalRpKeyMaterial;
use crate::Error;
use chrono::{DateTime, Duration, Utc};
use liblinkkeys::{encoding, identity_input::parse_identity_input, local_rp};
use serde::{Deserialize, Serialize};
use std::fmt;
use url::Url;

/// Default requested claims when the caller doesn't specify any (design doc,
/// "Default Claim Set"): a usable "identity" out of the box with zero claim
/// configuration.
pub const DEFAULT_REQUESTED_CLAIMS: &[&str] = &["display_name", "email", "handle"];
/// Default required claims (design doc, "Default Claim Set").
pub const DEFAULT_REQUIRED_CLAIMS: &[&str] = &["handle"];
/// Default login-request lifetime: short-lived, matching the callback's own
/// short default lifetime (design doc: "callback lifetime is short, default
/// 5 minutes").
pub const DEFAULT_LOGIN_REQUEST_LIFETIME: Duration = Duration::minutes(5);

/// Input to [`begin_local_login`]. Big-config, single struct.
#[derive(Clone)]
pub struct BeginLocalLoginConfig<'a> {
    /// The identity generated by [`crate::generate_local_rp_identity`]. Its
    /// already-signed descriptor is reused as-is in the login request — see
    /// [`LocalRpKeyMaterial`]'s docs for why this SDK doesn't re-sign a fresh
    /// descriptor per login.
    pub key_material: &'a LocalRpKeyMaterial,
    /// Where the IDP should redirect the browser back to after login. Must
    /// be `http://` or `https://` (design doc, "Callback URL Rules") — the
    /// IDP enforces this authoritatively, but this SDK checks it too so a
    /// misconfigured app fails fast instead of burning a round trip to
    /// discover it from the IDP's rejection page.
    pub callback_url: String,
    /// The LinkKeys login or domain that the user entered. A full login adds
    /// a username hint to the redirect. A bare domain selects only the IDP.
    pub user_domain: String,
    /// Requested (optional) claims. Defaults to [`DEFAULT_REQUESTED_CLAIMS`]
    /// when `None`.
    pub requested_claims: Option<Vec<String>>,
    /// Required claims — login fails at the IDP if the user can't/won't
    /// satisfy these. Defaults to [`DEFAULT_REQUIRED_CLAIMS`] when `None`.
    pub required_claims: Option<Vec<String>>,
    /// Optional number of distinct authentication factors to validate. The
    /// provider selects and validates the actual methods.
    pub minimum_factor_count: Option<i64>,
    /// Optional signed context. Use `claims_update` to ask the provider to
    /// reopen the user's prior claim choices instead of completing normal SSO.
    pub flow_context: Option<liblinkkeys::generated::types::AuthFlowContext>,
    /// Login-request lifetime from `now`. Defaults to
    /// [`DEFAULT_LOGIN_REQUEST_LIFETIME`] when `None`.
    pub request_lifetime: Option<Duration>,
    pub now: DateTime<Utc>,
    /// The DNS TXT lookup seam for browser endpoint discovery
    /// (`_linkkeys_apis.<user_domain>`, its `https=` endpoint). Defaults to
    /// [`crate::default_dns_resolver`] when `None`, same as
    /// [`crate::CompleteLocalLoginConfig::dns`]. Inject a fake in tests (no
    /// live DNS) or a hardened resolver in production.
    pub dns: Option<&'a dyn DnsResolver>,
}

// Hand-written because `dyn DnsResolver` has no `Debug`; the resolver is
// reported by presence only.
impl fmt::Debug for BeginLocalLoginConfig<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("BeginLocalLoginConfig")
            .field("key_material", &self.key_material)
            .field("callback_url", &self.callback_url)
            .field("user_domain", &self.user_domain)
            .field("requested_claims", &self.requested_claims)
            .field("required_claims", &self.required_claims)
            .field("minimum_factor_count", &self.minimum_factor_count)
            .field("flow_context", &self.flow_context)
            .field("request_lifetime", &self.request_lifetime)
            .field("now", &self.now)
            .field("dns", &self.dns.map(|_| "<injected>"))
            .finish()
    }
}

impl<'a> BeginLocalLoginConfig<'a> {
    /// Convenience constructor for the common case (default claims and
    /// lifetime).
    pub fn new(
        key_material: &'a LocalRpKeyMaterial,
        callback_url: impl Into<String>,
        user_domain: impl Into<String>,
        now: DateTime<Utc>,
    ) -> Self {
        Self {
            key_material,
            callback_url: callback_url.into(),
            user_domain: user_domain.into(),
            requested_claims: None,
            required_claims: None,
            minimum_factor_count: None,
            flow_context: None,
            request_lifetime: None,
            now,
            dns: None,
        }
    }
}

/// The redirect URL the app should send the user's browser to. The SDK never
/// performs the redirect itself (design doc: "Browser-only Flow" — "Opening
/// a browser is a UX decision outside the LinkKeys SDK").
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalLoginRedirect {
    pub redirect_url: String,
}

/// The state `begin_local_login` returns for the app to persist (e.g. in a
/// server-side session tied to the browser) and pass unchanged to
/// `complete_local_login`. **Single-use**: the design doc requires the app
/// discard it after one completion attempt — this crate cannot enforce that
/// itself (it owns no storage), so replay protection at the app boundary is
/// the app's responsibility.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PendingLogin {
    pub nonce: Vec<u8>,
    pub state: Vec<u8>,
    pub user_domain: String,
    pub callback_url: String,
    /// The claim types this login required (design doc, "Default Claim
    /// Set" / SEC checklist: "the app-declared required claims are
    /// actually enforced"). `complete_local_login` re-checks this set
    /// against the redemption's verified claims — it must round-trip
    /// through whatever storage the app persists `PendingLogin` in, so a
    /// login that began requiring e.g. `handle` can't complete without it
    /// just because the requirement was forgotten between `begin` and
    /// `complete`.
    pub required_claims: Vec<String>,
}

fn validate_callback_scheme(url: &str) -> Result<(), Error> {
    if url.starts_with("http://") || url.starts_with("https://") {
        Ok(())
    } else {
        Err(Error::InvalidInput(format!(
            "callback_url must be http:// or https://, got: {url:?}"
        )))
    }
}

/// `begin_local_login(config) -> (LocalLoginRedirect, PendingLogin)` (design
/// doc, "SDK API Shape"). Generates a fresh nonce/state, builds and signs a
/// `LocalRpLoginRequest` (envelope + `linkkeys-local-rp-login-request-v1alpha`
/// context) around the identity's descriptor, and returns the full redirect
/// URL for the user's LinkKeys domain plus the pending-login state.
///
/// The redirect host comes from `_linkkeys_apis.<user_domain>` discovery
/// ([`crate::resolve_browser_base`]) with a fallback to the identity domain
/// itself. [`PendingLogin::user_domain`] stays the identity domain —
/// verification is bound to it, never to the discovered service host.
pub fn begin_local_login(
    config: BeginLocalLoginConfig<'_>,
) -> Result<(LocalLoginRedirect, PendingLogin), Error> {
    validate_callback_scheme(&config.callback_url)?;
    let identity = parse_identity_input(&config.user_domain)
        .map_err(|error| Error::InvalidInput(error.to_string()))?;

    let nonce: [u8; 32] = rand::random();
    let state: [u8; 32] = rand::random();

    let requested_claims = config.requested_claims.unwrap_or_else(|| {
        DEFAULT_REQUESTED_CLAIMS
            .iter()
            .map(|s| s.to_string())
            .collect()
    });
    let required_claims = config.required_claims.unwrap_or_else(|| {
        DEFAULT_REQUIRED_CLAIMS
            .iter()
            .map(|s| s.to_string())
            .collect()
    });
    let lifetime = config
        .request_lifetime
        .unwrap_or(DEFAULT_LOGIN_REQUEST_LIFETIME);
    let issued_at = config.now.to_rfc3339();
    let expires_at = (config.now + lifetime).to_rfc3339();

    // Cloned before the move below: `PendingLogin` must retain the same
    // required-claim set so `complete_local_login` can enforce it later.
    let pending_required_claims = required_claims.clone();

    let mut request = local_rp::build_local_rp_login_request(
        config.key_material.descriptor.clone(),
        &config.callback_url,
        nonce.to_vec(),
        state.to_vec(),
        requested_claims,
        required_claims,
        &issued_at,
        &expires_at,
    );
    request.authentication_requirements = config.minimum_factor_count.map(|minimum_factor_count| {
        liblinkkeys::generated::types::AuthenticationRequirements {
            minimum_factor_count,
        }
    });
    request.flow_context = config.flow_context;
    let signed =
        local_rp::sign_local_rp_login_request(&request, &config.key_material.signing_private_key)
            .map_err(Error::from)?;

    let encoded = encoding::signed_local_rp_login_request_to_url_param(&signed)
        .map_err(|e| Error::Decode(e.to_string()))?;

    // Wire Precision: "Begin route: GET /auth/local-rp?signed_request=<...>"
    // — mirrors the existing GET /auth/authorize?signed_request=... shape.
    // The host comes from `_linkkeys_apis.<user_domain>` discovery (with a
    // fallback to the identity domain itself); `PendingLogin::user_domain`
    // stays the identity domain — verification is bound to it, never to the
    // discovered service host.
    let dns: &dyn DnsResolver = match config.dns {
        Some(dns) => dns,
        None => crate::default_dns_resolver(),
    };
    let mut redirect_url =
        resolve_browser_endpoint(dns, &identity.domain, BROWSER_ROUTE_LOCAL_RP, &encoded)?;
    if let Some(username) = identity.username {
        let mut parsed = Url::parse(&redirect_url)
            .map_err(|_| Error::InvalidInput("browser endpoint produced an invalid URL".into()))?;
        parsed.query_pairs_mut().append_pair("username", &username);
        redirect_url = parsed.into();
    }

    Ok((
        LocalLoginRedirect { redirect_url },
        PendingLogin {
            nonce: nonce.to_vec(),
            state: state.to_vec(),
            user_domain: identity.domain,
            callback_url: config.callback_url,
            required_claims: pending_required_claims,
        },
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::browser::tests::MapDnsResolver;
    use crate::identity::{generate_local_rp_identity, GenerateLocalRpIdentityConfig};

    const DOMAIN: &str = "ident.example.test";

    fn material() -> LocalRpKeyMaterial {
        generate_local_rp_identity(GenerateLocalRpIdentityConfig::new("Test App", Utc::now()))
            .unwrap()
    }

    /// A config whose resolver always fails: every test here is hermetic
    /// (no live DNS), and the failure exercises the identity-domain
    /// fallback the pre-discovery tests were written against.
    fn config_with<'a>(
        m: &'a LocalRpKeyMaterial,
        dns: &'a dyn DnsResolver,
        user_domain: &str,
    ) -> BeginLocalLoginConfig<'a> {
        let mut config = BeginLocalLoginConfig::new(
            m,
            "http://localhost:8080/callback",
            user_domain,
            Utc::now(),
        );
        config.dns = Some(dns);
        config
    }

    fn begin_with(dns: &dyn DnsResolver) -> (LocalLoginRedirect, PendingLogin) {
        let m = material();
        begin_local_login(config_with(&m, dns, DOMAIN)).unwrap()
    }

    #[test]
    fn begin_defaults_claims_and_produces_pending_state() {
        let m = material();
        let dns = MapDnsResolver::failing("SERVFAIL");
        let (redirect, pending) = begin_local_login(config_with(&m, &dns, "example.com")).unwrap();

        assert!(redirect
            .redirect_url
            .starts_with("https://example.com/auth/local-rp?signed_request="));
        assert_eq!(pending.user_domain, "example.com");
        assert_eq!(pending.callback_url, "http://localhost:8080/callback");
        assert_eq!(pending.nonce.len(), 32);
        assert_eq!(pending.state.len(), 32);
        assert_eq!(
            pending.required_claims,
            DEFAULT_REQUIRED_CLAIMS
                .iter()
                .map(|s| s.to_string())
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn full_login_adds_username_hint_and_binds_pending_to_domain() {
        let m = material();
        let dns = MapDnsResolver::failing("SERVFAIL");
        let (redirect, pending) =
            begin_local_login(config_with(&m, &dns, "Alice+work@ID.Example.COM")).unwrap();

        assert!(redirect
            .redirect_url
            .starts_with("https://id.example.com/auth/local-rp?signed_request="));
        assert!(redirect.redirect_url.ends_with("&username=Alice%2Bwork"));
        assert_eq!(pending.user_domain, "id.example.com");
    }

    #[test]
    fn malformed_identity_is_rejected() {
        let m = material();
        let dns = MapDnsResolver::failing("SERVFAIL");
        for input in ["alice", "alice@@example.com", "https://example.com"] {
            let result = begin_local_login(config_with(&m, &dns, input));
            assert!(result.is_err(), "accepted {input:?}");
        }
    }

    #[test]
    fn begin_retains_caller_supplied_required_claims_in_pending_state() {
        let m = material();
        let dns = MapDnsResolver::failing("SERVFAIL");
        let mut config = config_with(&m, &dns, "example.com");
        config.required_claims = Some(vec!["email".to_string(), "handle".to_string()]);
        let (_, pending) = begin_local_login(config).unwrap();
        assert_eq!(
            pending.required_claims,
            vec!["email".to_string(), "handle".to_string()]
        );
    }

    #[test]
    fn begin_rejects_non_http_callback_scheme() {
        let m = material();
        let dns = MapDnsResolver::failing("SERVFAIL");
        let mut config = config_with(&m, &dns, "example.com");
        config.callback_url = "myapp://callback".to_string();
        let result = begin_local_login(config);
        assert!(matches!(result, Err(Error::InvalidInput(_))));
    }

    #[test]
    fn begin_two_calls_never_reuse_nonce_or_state() {
        let dns = MapDnsResolver::failing("SERVFAIL");
        let (_, p1) = begin_with(&dns);
        let (_, p2) = begin_with(&dns);
        assert_ne!(p1.nonce, p2.nonce);
        assert_ne!(p1.state, p2.state);
    }

    #[test]
    fn pending_login_is_serializable() {
        let dns = MapDnsResolver::failing("SERVFAIL");
        let (_, pending) = begin_with(&dns);
        let json = serde_json::to_string(&pending).unwrap();
        let round_tripped: PendingLogin = serde_json::from_str(&json).unwrap();
        assert_eq!(round_tripped, pending);
    }

    // -----------------------------------------------------------------
    // Browser endpoint discovery (parity with sdks/local-rp/go/browser_test.go)
    // -----------------------------------------------------------------

    // Case 1: a valid https= host is used for the redirect instead of the
    // identity domain. Case 8: PendingLogin.user_domain stays the identity
    // domain — verification stays bound to it, not to the service host.
    #[test]
    fn begin_uses_discovered_https_host() {
        let dns = MapDnsResolver::apis(
            DOMAIN,
            &["v=lk1 tcp=linkkeys.ident.example.test https=linkkeys.ident.example.test"],
        );
        let (redirect, pending) = begin_with(&dns);
        assert!(
            redirect
                .redirect_url
                .starts_with("https://linkkeys.ident.example.test/auth/local-rp?signed_request="),
            "{}",
            redirect.redirect_url
        );
        assert!(!redirect
            .redirect_url
            .starts_with(&format!("https://{DOMAIN}/")));
        assert_eq!(pending.user_domain, DOMAIN);
    }

    // Case 2: an https= value with a path prefix preserves that prefix.
    #[test]
    fn begin_preserves_https_path_prefix() {
        let dns = MapDnsResolver::apis(DOMAIN, &["v=lk1 https=login.example.test/linkkeys"]);
        let (redirect, _) = begin_with(&dns);
        assert!(
            redirect
                .redirect_url
                .starts_with("https://login.example.test/linkkeys/auth/local-rp?signed_request="),
            "{}",
            redirect.redirect_url
        );
    }

    // Case 3: a record with only tcp= falls back to the identity domain.
    #[test]
    fn begin_tcp_only_record_falls_back_to_identity_domain() {
        let dns = MapDnsResolver::apis(DOMAIN, &["v=lk1 tcp=linkkeys.ident.example.test"]);
        let (redirect, _) = begin_with(&dns);
        assert!(redirect
            .redirect_url
            .starts_with(&format!("https://{DOMAIN}/auth/local-rp?signed_request=")));
    }

    // Case 4: a DNS lookup error falls back to the identity domain.
    #[test]
    fn begin_dns_error_falls_back_to_identity_domain() {
        let dns = MapDnsResolver::failing("SERVFAIL");
        let (redirect, _) = begin_with(&dns);
        assert!(redirect
            .redirect_url
            .starts_with(&format!("https://{DOMAIN}/auth/local-rp?signed_request=")));
    }

    // Cases 5 + 6: invalid TXT records are ignored, and across several
    // records the FIRST valid record with https= is selected.
    #[test]
    fn begin_selects_first_valid_https_across_records() {
        let dns = MapDnsResolver::apis(
            DOMAIN,
            &[
                "not a linkkeys record",
                "v=lk2 https=wrong-version.example.test",
                "v=lk1 tcp=tcp-only.example.test",
                "v=lk1 https=first.example.test",
                "v=lk1 https=second.example.test",
            ],
        );
        let (redirect, _) = begin_with(&dns);
        assert!(
            redirect
                .redirect_url
                .starts_with("https://first.example.test/auth/local-rp?signed_request="),
            "{}",
            redirect.redirect_url
        );
    }

    // Case 7: signed_request rides the discovered URL unchanged — it decodes
    // to the signed login request whose fields match this login.
    #[test]
    fn begin_signed_request_survives_discovered_url() {
        let dns = MapDnsResolver::apis(DOMAIN, &["v=lk1 https=login.example.test/linkkeys"]);
        let (redirect, pending) = begin_with(&dns);
        let url = Url::parse(&redirect.redirect_url).unwrap();
        let param = url
            .query_pairs()
            .find(|(k, _)| k == "signed_request")
            .map(|(_, v)| v.into_owned())
            .expect("signed_request query parameter missing");
        let signed = encoding::signed_local_rp_login_request_from_url_param(&param).unwrap();
        let request =
            liblinkkeys::generated::decode_local_rp_login_request(&signed.request).unwrap();
        assert_eq!(request.callback_url, pending.callback_url);
        assert_eq!(request.nonce, pending.nonce);
    }

    // Case 9: a config built without touching `dns` compiles unchanged and
    // defaults to the memoized system resolver. The default path is not
    // executed here — that would be a live DNS request.
    #[test]
    fn begin_config_without_resolver_still_compiles() {
        let m = material();
        let config =
            BeginLocalLoginConfig::new(&m, "http://localhost:8080/callback", DOMAIN, Utc::now());
        assert!(config.dns.is_none());
        let _default: &dyn DnsResolver = crate::default_dns_resolver();
    }
}
