apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkkeys.fullname" . }}
  labels:
    {{- include "linkkeys.labels" . | nindent 4 }}
data:
  DATABASE_BACKEND: {{ .Values.database.backend | quote }}
  LOG_LEVEL: {{ .Values.server.logLevel | quote }}
  TCP_PORT: {{ .Values.server.tcpPort | quote }}
  HTTPS_PORT: {{ .Values.server.httpsPort | quote }}
  {{- if .Values.server.domainName }}
  DOMAIN_NAME: {{ .Values.server.domainName | quote }}
  {{- end }}
  {{- if .Values.server.apiHostname }}
  API_HOSTNAME: {{ .Values.server.apiHostname | quote }}
  {{- end }}
  {{- if .Values.server.publicPort }}
  PUBLIC_PORT: {{ .Values.server.publicPort | quote }}
  {{- end }}
  DISABLE_TCP_TLS: {{ .Values.server.disableTcpTls | quote }}
  {{- if eq .Values.server.disableTls "true" }}
  DISABLE_TLS: "true"
  {{- end }}
  {{- if .Values.rp.enabled }}
  ENABLE_RP_ENDPOINTS: "true"
  {{- end }}
  {{- if .Values.rp.apiKeyAuth }}
  ENABLE_API_KEY_AUTH: "true"
  {{- end }}
  {{- if not .Values.rp.passwordAuth }}
  ENABLE_PASSWORD_AUTH: "false"
  {{- end }}
  {{- if eq .Values.rp.allowInvalidCerts "true" }}
  ALLOW_INVALID_CERTS: "true"
  {{- end }}
