apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkkeys.fullname" . }}
  labels:
    {{- include "linkkeys.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  {{- if .Values.server.domainKeyPassphrase }}
  DOMAIN_KEY_PASSPHRASE: {{ .Values.server.domainKeyPassphrase | b64enc | quote }}
  {{- end }}
