# For the catalyst-helm/pysocha-site helm chart
# See https://github.com/catalystcommunity/chart-pysocha-site

domain: catalystlinkkeys.com
sitefilePath: "/site/root"
image:
  repository: 10.16.0.1:5000/public/catalystcommunity/linkkeys-website
  # tag will be provided by --set image.tag=...
