//! `beginLocalLogin` (design doc: "SDK API Shape", "Flow" steps 4-6).
//! Mirrors `sdks/local-rp/rust/src/begin.rs` / `sdks/local-rp/go/begin.go`.
//!
//! Pure/offline: no network access happens here. It generates a fresh
//! nonce/state, builds and signs a `LocalRpLoginRequest` around the
//! identity's already-signed descriptor, and returns a redirect URL plus
//! the pending-login state the app must persist and treat as single-use.

const std = @import("std");
const identity = @import("identity.zig");
const local_rp = @import("local_rp.zig");
const encoding = @import("encoding.zig");
const xcrypto = @import("crypto.zig");

/// Default requested claims when the caller doesn't specify any (design
/// doc, "Default Claim Set"): a usable "identity" out of the box with zero
/// claim configuration.
pub const default_requested_claims = [_][]const u8{ "display_name", "email", "handle" };

/// Default required claims (design doc, "Default Claim Set").
pub const default_required_claims = [_][]const u8{"handle"};

/// Default login-request lifetime: short-lived, matching the callback's own
/// short default lifetime (design doc: "callback lifetime is short, default
/// 5 minutes").
pub const default_login_request_lifetime_seconds: i64 = 5 * 60;

/// Input to `beginLocalLogin`. Big-config, single struct (design doc: "big
/// config, single-function APIs first").
pub const BeginLocalLoginConfig = struct {
    /// The identity generated by `generateLocalRpIdentity`. Its
    /// already-signed descriptor is reused as-is in the login request.
    key_material: identity.LocalRpKeyMaterial,
    /// Where the IDP should redirect the browser back to after login. Must
    /// be `http://` or `https://` (design doc, "Callback URL Rules") — the
    /// IDP enforces this authoritatively, but this SDK checks it too so a
    /// misconfigured app fails fast.
    callback_url: []const u8,
    /// The LinkKeys domain the user selected/entered.
    user_domain: []const u8,
    /// Optional requested claims. Defaults to `default_requested_claims`
    /// when null.
    requested_claims: ?[]const []const u8 = null,
    /// Required claims — login fails at the IDP if the user can't/won't
    /// satisfy these. Defaults to `default_required_claims` when null.
    required_claims: ?[]const []const u8 = null,
    /// Login-request lifetime from `now`. Defaults to
    /// `default_login_request_lifetime_seconds` when zero.
    request_lifetime_seconds: i64 = 0,
    now: i64,
};

/// The redirect URL the app should send the user's browser to. The SDK
/// never performs the redirect itself (design doc: "Browser-only Flow" —
/// opening a browser is a UX decision outside the LinkKeys SDK).
pub const LocalLoginRedirect = struct {
    redirect_url: []const u8,
};

/// State `beginLocalLogin` returns for the app to persist (e.g. in a
/// server-side session tied to the browser) and pass unchanged to
/// `completeLocalLogin`. Single-use: the design doc requires the app
/// discard it after one completion attempt — this package cannot enforce
/// that itself (it owns no storage), so replay protection at the app
/// boundary is the app's responsibility.
pub const PendingLogin = struct {
    nonce: []const u8,
    state: []const u8,
    user_domain: []const u8,
    callback_url: []const u8,
    /// The claim types this login required (design doc, "Default Claim
    /// Set" / SEC checklist: "the app-declared required claims are
    /// actually enforced"). `completeLocalLogin` re-checks this set against
    /// the redemption's verified claims — it must round-trip through
    /// whatever storage the app persists `PendingLogin` in, so a login that
    /// began requiring e.g. `handle` can't complete without it just because
    /// the requirement was forgotten between begin and complete.
    required_claims: []const []const u8,
};

pub const BeginLocalLoginResult = struct {
    redirect: LocalLoginRedirect,
    pending: PendingLogin,
};

fn validateCallbackScheme(url: []const u8) !void {
    if (std.mem.startsWith(u8, url, "http://") or std.mem.startsWith(u8, url, "https://")) return;
    return error.InvalidCallbackScheme;
}

/// Implements `begin_local_login(config) -> (LocalLoginRedirect,
/// PendingLogin)` (design doc, "SDK API Shape"). Generates a fresh
/// nonce/state, builds and signs a `LocalRpLoginRequest` (envelope +
/// `linkkeys-local-rp-login-request` context) around the identity's
/// descriptor, and returns the full redirect URL for the user's LinkKeys
/// domain plus the pending-login state.
pub fn beginLocalLogin(allocator: std.mem.Allocator, config: BeginLocalLoginConfig) !BeginLocalLoginResult {
    try validateCallbackScheme(config.callback_url);
    if (std.mem.trim(u8, config.user_domain, " \t\r\n").len == 0) return error.InvalidInput;

    var nonce: [32]u8 = undefined;
    xcrypto.randomBytes(&nonce);
    var state: [32]u8 = undefined;
    xcrypto.randomBytes(&state);
    const nonce_owned = try allocator.dupe(u8, &nonce);
    const state_owned = try allocator.dupe(u8, &state);

    const requested_claims = config.requested_claims orelse &default_requested_claims;
    const required_claims = config.required_claims orelse &default_required_claims;
    const lifetime = if (config.request_lifetime_seconds == 0) default_login_request_lifetime_seconds else config.request_lifetime_seconds;

    var issued_buf: [32]u8 = undefined;
    var expires_buf: [32]u8 = undefined;
    const issued_at = try allocator.dupe(u8, try local_rp.formatTimestamp(&issued_buf, config.now));
    const expires_at = try allocator.dupe(u8, try local_rp.formatTimestamp(&expires_buf, config.now + lifetime));

    const request = local_rp.buildLocalRpLoginRequest(config.key_material.descriptor, config.callback_url, nonce_owned, state_owned, requested_claims, required_claims, issued_at, expires_at);
    const signed = try local_rp.signLocalRpLoginRequest(allocator, request, config.key_material.signing_private_key);

    const encoded = try encoding.signedLocalRpLoginRequestToUrlParam(allocator, signed);

    // Wire Precision: "Begin route: GET /auth/local-rp?signed_request=<...>"
    // — mirrors the existing GET /auth/authorize?signed_request=... shape.
    const redirect_url = try std.fmt.allocPrint(allocator, "https://{s}/auth/local-rp?signed_request={s}", .{ config.user_domain, encoded });

    return .{
        .redirect = .{ .redirect_url = redirect_url },
        .pending = .{ .nonce = nonce_owned, .state = state_owned, .user_domain = config.user_domain, .callback_url = config.callback_url, .required_claims = required_claims },
    };
}

test "beginLocalLogin rejects non-http(s) callback schemes" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try identity.generateLocalRpIdentity(a, .{ .app_name = "Test App", .now = now });

    try std.testing.expectError(error.InvalidCallbackScheme, beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "myapp://callback",
        .user_domain = "example.com",
        .now = now,
    }));
}

test "beginLocalLogin produces a redirect URL and single-use pending state" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try identity.generateLocalRpIdentity(a, .{ .app_name = "Test App", .now = now });

    const result = try beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "http://jukebox.lan:8080/auth/callback",
        .user_domain = "example.com",
        .now = now,
    });

    try std.testing.expect(std.mem.startsWith(u8, result.redirect.redirect_url, "https://example.com/auth/local-rp?signed_request="));
    try std.testing.expectEqual(@as(usize, 32), result.pending.nonce.len);
    try std.testing.expectEqual(@as(usize, 32), result.pending.state.len);
    try std.testing.expectEqualStrings("example.com", result.pending.user_domain);
    try std.testing.expectEqual(@as(usize, 1), result.pending.required_claims.len);
    try std.testing.expectEqualStrings("handle", result.pending.required_claims[0]);
}

test "beginLocalLogin retains caller-supplied required claims in the pending state" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try identity.generateLocalRpIdentity(a, .{ .app_name = "Test App", .now = now });

    const custom_required = [_][]const u8{ "email", "handle" };
    const result = try beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "http://localhost/callback",
        .user_domain = "example.com",
        .required_claims = &custom_required,
        .now = now,
    });

    try std.testing.expectEqual(@as(usize, 2), result.pending.required_claims.len);
    try std.testing.expectEqualStrings("email", result.pending.required_claims[0]);
    try std.testing.expectEqualStrings("handle", result.pending.required_claims[1]);
}

test "PendingLogin.required_claims round-trips through JSON (the app's own serialize form)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try identity.generateLocalRpIdentity(a, .{ .app_name = "Test App", .now = now });

    const custom_required = [_][]const u8{ "email", "handle" };
    const result = try beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "http://localhost/callback",
        .user_domain = "example.com",
        .required_claims = &custom_required,
        .now = now,
    });

    const json_bytes = try std.json.stringifyAlloc(a, result.pending, .{});
    const parsed = try std.json.parseFromSlice(PendingLogin, a, json_bytes, .{});
    defer parsed.deinit();

    try std.testing.expectEqual(@as(usize, 2), parsed.value.required_claims.len);
    try std.testing.expectEqualStrings("email", parsed.value.required_claims[0]);
    try std.testing.expectEqualStrings("handle", parsed.value.required_claims[1]);
    try std.testing.expectEqualStrings(result.pending.user_domain, parsed.value.user_domain);
}
