//! `beginLocalLogin` (design doc: "SDK API Shape", "Flow" steps 4-6).
//! Mirrors `sdks/local-rp/rust/src/begin.rs` / `sdks/local-rp/go/begin.go`.
//!
//! It generates a fresh nonce/state, builds and signs a `LocalRpLoginRequest`
//! around the identity's already-signed descriptor, and returns a redirect
//! URL plus the pending-login state the app must persist and treat as
//! single-use.
//!
//! The signing work is pure/offline. The one network touch is a DNS TXT
//! lookup of `_linkkeys_apis.<user_domain>` to discover the browser-facing
//! HTTPS endpoint (the identity domain is a trust domain, not necessarily
//! the host serving the login routes — see `browser.zig`). The resolver is
//! injectable via `BeginLocalLoginConfig.dns`; on any discovery failure the
//! redirect falls back to `https://<user_domain>`.

const std = @import("std");
const identity = @import("identity.zig");
const local_rp = @import("local_rp.zig");
const encoding = @import("encoding.zig");
const xcrypto = @import("crypto.zig");
const dnsmod = @import("dns.zig");
const browser = @import("browser.zig");

/// Default requested claims when the caller doesn't specify any (design
/// doc, "Default Claim Set"): a usable "identity" out of the box with zero
/// claim configuration.
pub const default_requested_claims = [_][]const u8{ "display_name", "email", "handle" };

/// Default required claims (design doc, "Default Claim Set").
pub const default_required_claims = [_][]const u8{"handle"};

/// Default login-request lifetime: short-lived, matching the callback's own
/// short default lifetime (design doc: "callback lifetime is short, default
/// 5 minutes").
pub const default_login_request_lifetime_seconds: i64 = 5 * 60;

/// Input to `beginLocalLogin`. Big-config, single struct (design doc: "big
/// config, single-function APIs first").
pub const BeginLocalLoginConfig = struct {
    /// The identity generated by `generateLocalRpIdentity`. Its
    /// already-signed descriptor is reused as-is in the login request.
    key_material: identity.LocalRpKeyMaterial,
    /// Where the IDP should redirect the browser back to after login. Must
    /// be `http://` or `https://` (design doc, "Callback URL Rules") — the
    /// IDP enforces this authoritatively, but this SDK checks it too so a
    /// misconfigured app fails fast.
    callback_url: []const u8,
    /// The LinkKeys login or domain. A full login adds a username hint.
    user_domain: []const u8,
    /// Optional requested claims. Defaults to `default_requested_claims`
    /// when null.
    requested_claims: ?[]const []const u8 = null,
    /// Required claims — login fails at the IDP if the user can't/won't
    /// satisfy these. Defaults to `default_required_claims` when null.
    required_claims: ?[]const []const u8 = null,
    /// Login-request lifetime from `now`. Defaults to
    /// `default_login_request_lifetime_seconds` when zero.
    request_lifetime_seconds: i64 = 0,
    now: i64,
    /// The DNS TXT lookup seam for browser endpoint discovery
    /// (`_linkkeys_apis.<user_domain>`, its `https=` endpoint). Defaults to
    /// the system resolver (`dns.SystemDnsResolver`) when null, same seam
    /// as `CompleteLocalLoginConfig.dns`. Inject a fake in tests (no live
    /// DNS) or a hardened resolver in production.
    dns: ?dnsmod.DnsResolver = null,
};

/// The redirect URL the app should send the user's browser to. The SDK
/// never performs the redirect itself (design doc: "Browser-only Flow" —
/// opening a browser is a UX decision outside the LinkKeys SDK).
pub const LocalLoginRedirect = struct {
    redirect_url: []const u8,
};

/// State `beginLocalLogin` returns for the app to persist (e.g. in a
/// server-side session tied to the browser) and pass unchanged to
/// `completeLocalLogin`. Single-use: the design doc requires the app
/// discard it after one completion attempt — this package cannot enforce
/// that itself (it owns no storage), so replay protection at the app
/// boundary is the app's responsibility.
pub const PendingLogin = struct {
    nonce: []const u8,
    state: []const u8,
    user_domain: []const u8,
    callback_url: []const u8,
    /// The claim types this login required (design doc, "Default Claim
    /// Set" / SEC checklist: "the app-declared required claims are
    /// actually enforced"). `completeLocalLogin` re-checks this set against
    /// the redemption's verified claims — it must round-trip through
    /// whatever storage the app persists `PendingLogin` in, so a login that
    /// began requiring e.g. `handle` can't complete without it just because
    /// the requirement was forgotten between begin and complete.
    required_claims: []const []const u8,
};

pub const BeginLocalLoginResult = struct {
    redirect: LocalLoginRedirect,
    pending: PendingLogin,
};

pub fn validateCallbackScheme(url: []const u8) !void {
    if (std.mem.startsWith(u8, url, "http://") or std.mem.startsWith(u8, url, "https://")) return;
    return error.InvalidCallbackScheme;
}

pub const IdentityInput = struct {
    username: ?[]const u8,
    domain: []const u8,
};

fn invalidIdentity() error{InvalidInput} {
    return error.InvalidInput;
}

pub fn parseIdentityInput(allocator: std.mem.Allocator, value: []const u8) !IdentityInput {
    const input = std.mem.trim(u8, value, " \t\r\n");
    if (input.len == 0) return invalidIdentity();
    var at: ?usize = null;
    for (input, 0..) |c, i| {
        if (c > 127) return invalidIdentity();
        if (c == '@') {
            if (at != null) return invalidIdentity();
            at = i;
        }
    }
    const username = if (at) |i| input[0..i] else null;
    const domain_source = if (at) |i| input[i + 1 ..] else input;
    if (username) |name| {
        if (name.len == 0 or name.len > 64 or name[0] == '.' or name[name.len - 1] == '.') return invalidIdentity();
        var previous_dot = false;
        for (name) |c| {
            const valid = std.ascii.isAlphanumeric(c) or std.mem.indexOfScalar(u8, "!#$%&'*+-/=?^_`{|}~.", c) != null;
            if (!valid or (c == '.' and previous_dot)) return invalidIdentity();
            previous_dot = c == '.';
        }
    }
    if (!validIdentityDomain(domain_source)) return invalidIdentity();
    const domain = try allocator.dupe(u8, domain_source);
    for (domain) |*c| c.* = std.ascii.toLower(c.*);
    return .{ .username = username, .domain = domain };
}

fn validIdentityDomain(domain: []const u8) bool {
    if (domain.len == 0 or domain.len > 259) return false;
    var host = domain;
    var has_port = false;
    if (std.mem.lastIndexOfScalar(u8, domain, ':')) |separator| {
        if (std.mem.indexOfScalar(u8, domain, ':').? != separator) return false;
        const port_text = domain[separator + 1 ..];
        if (port_text.len == 0) return false;
        for (port_text) |c| if (!std.ascii.isDigit(c)) return false;
        const port = std.fmt.parseInt(u16, port_text, 10) catch return false;
        if (port == 0) return false;
        host = domain[0..separator];
        has_port = true;
    }
    if (host.len == 0 or host.len > 253 or (std.mem.indexOfScalar(u8, host, '.') == null and !has_port)) return false;
    var labels = std.mem.splitScalar(u8, host, '.');
    while (labels.next()) |label| {
        if (label.len == 0 or label.len > 63 or label[0] == '-' or label[label.len - 1] == '-') return false;
        for (label) |c| if (!std.ascii.isAlphanumeric(c) and c != '-') return false;
    }
    return true;
}

fn percentEncodeUsername(username: []const u8, output: *[192]u8) []const u8 {
    const hex = "0123456789ABCDEF";
    var offset: usize = 0;
    for (username) |c| {
        if (std.ascii.isAlphanumeric(c) or c == '-' or c == '.' or c == '_' or c == '~') {
            output[offset] = c;
            offset += 1;
        } else {
            output[offset] = '%';
            output[offset + 1] = hex[c >> 4];
            output[offset + 2] = hex[c & 15];
            offset += 3;
        }
    }
    return output[0..offset];
}

/// Implements `begin_local_login(config) -> (LocalLoginRedirect,
/// PendingLogin)` (design doc, "SDK API Shape"). Generates a fresh
/// nonce/state, builds and signs a `LocalRpLoginRequest` (envelope +
/// `linkkeys-local-rp-login-request-v1alpha` context) around the identity's
/// descriptor, and returns the full redirect URL for the user's LinkKeys
/// domain plus the pending-login state.
pub fn beginLocalLogin(allocator: std.mem.Allocator, config: BeginLocalLoginConfig) !BeginLocalLoginResult {
    try validateCallbackScheme(config.callback_url);
    const identity_input = try parseIdentityInput(allocator, config.user_domain);

    var nonce: [32]u8 = undefined;
    xcrypto.randomBytes(&nonce);
    var state: [32]u8 = undefined;
    xcrypto.randomBytes(&state);
    const nonce_owned = try allocator.dupe(u8, &nonce);
    const state_owned = try allocator.dupe(u8, &state);

    const requested_claims = config.requested_claims orelse &default_requested_claims;
    const required_claims = config.required_claims orelse &default_required_claims;
    const lifetime = if (config.request_lifetime_seconds == 0) default_login_request_lifetime_seconds else config.request_lifetime_seconds;

    var issued_buf: [32]u8 = undefined;
    var expires_buf: [32]u8 = undefined;
    const issued_at = try allocator.dupe(u8, try local_rp.formatTimestamp(&issued_buf, config.now));
    const expires_at = try allocator.dupe(u8, try local_rp.formatTimestamp(&expires_buf, config.now + lifetime));

    const request = local_rp.buildLocalRpLoginRequest(config.key_material.descriptor, config.callback_url, nonce_owned, state_owned, requested_claims, required_claims, issued_at, expires_at);
    const signed = try local_rp.signLocalRpLoginRequest(allocator, request, config.key_material.signing_private_key);

    const encoded = try encoding.signedLocalRpLoginRequestToUrlParam(allocator, signed);

    // Wire Precision: "Begin route: GET /auth/local-rp?signed_request=<...>"
    // — mirrors the existing GET /auth/authorize?signed_request=... shape.
    // The host comes from `_linkkeys_apis.<user_domain>` discovery (with a
    // fallback to the identity domain itself); `PendingLogin.user_domain`
    // stays the identity domain — verification is bound to it, never to the
    // discovered service host.
    var system_resolver: dnsmod.SystemDnsResolver = undefined;
    const resolver: ?dnsmod.DnsResolver = config.dns orelse blk: {
        // No nameserver at all is a discovery failure like any other: the
        // composition falls back to the identity domain.
        system_resolver = dnsmod.SystemDnsResolver.init() catch break :blk null;
        break :blk system_resolver.resolver();
    };
    const endpoint = try browser.resolveBrowserEndpoint(allocator, resolver, identity_input.domain, browser.browser_route_local_rp, encoded);
    // The endpoint's query is exactly `signed_request=<value>` (no
    // fragment), so appending one more encoded pair is well-formed.
    var username_buffer: [192]u8 = undefined;
    const redirect_url = if (identity_input.username) |username|
        try std.fmt.allocPrint(allocator, "{s}&username={s}", .{ endpoint, percentEncodeUsername(username, &username_buffer) })
    else
        endpoint;

    return .{
        .redirect = .{ .redirect_url = redirect_url },
        .pending = .{ .nonce = nonce_owned, .state = state_owned, .user_domain = identity_input.domain, .callback_url = config.callback_url, .required_claims = required_claims },
    };
}

// ---------------------------------------------------------------------
// Tests. Every test injects a `browser.FakeDnsResolver` (canned answers or
// a hard failure) — no test here performs a live DNS request.
// ---------------------------------------------------------------------

const FakeDnsResolver = browser.FakeDnsResolver;
const test_domain = "ident.example.test";

fn testKeyMaterial(a: std.mem.Allocator, now: i64) !identity.LocalRpKeyMaterial {
    return identity.generateLocalRpIdentity(a, .{ .app_name = "Test App", .now = now });
}

fn beginWith(a: std.mem.Allocator, fake: *FakeDnsResolver) !BeginLocalLoginResult {
    const now: i64 = try local_rp.parseTimestamp("2026-08-17T12:00:00Z");
    const km = try testKeyMaterial(a, now);
    return beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "http://app.lan:8080/cb",
        .user_domain = test_domain,
        .now = now,
        .dns = fake.resolver(),
    });
}

test "beginLocalLogin rejects non-http(s) callback schemes" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try testKeyMaterial(a, now);
    var failing = FakeDnsResolver.failing();

    try std.testing.expectError(error.InvalidCallbackScheme, beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "myapp://callback",
        .user_domain = "example.com",
        .now = now,
        .dns = failing.resolver(),
    }));
}

test "beginLocalLogin produces a redirect URL and single-use pending state" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try testKeyMaterial(a, now);
    var failing = FakeDnsResolver.failing();

    const result = try beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "http://jukebox.lan:8080/auth/callback",
        .user_domain = "example.com",
        .now = now,
        .dns = failing.resolver(),
    });

    try std.testing.expect(std.mem.startsWith(u8, result.redirect.redirect_url, "https://example.com/auth/local-rp?signed_request="));
    try std.testing.expectEqual(@as(usize, 32), result.pending.nonce.len);
    try std.testing.expectEqual(@as(usize, 32), result.pending.state.len);
    try std.testing.expectEqualStrings("example.com", result.pending.user_domain);
    try std.testing.expectEqual(@as(usize, 1), result.pending.required_claims.len);
    try std.testing.expectEqualStrings("handle", result.pending.required_claims[0]);
}

test "beginLocalLogin parses identity input" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try testKeyMaterial(a, now);
    var failing = FakeDnsResolver.failing();
    const result = try beginLocalLogin(a, .{ .key_material = km, .callback_url = "http://localhost/callback", .user_domain = "Alice+work@ID.Example.TEST", .now = now, .dns = failing.resolver() });
    try std.testing.expect(std.mem.startsWith(u8, result.redirect.redirect_url, "https://id.example.test/auth/local-rp?signed_request="));
    try std.testing.expect(std.mem.endsWith(u8, result.redirect.redirect_url, "&username=Alice%2Bwork"));
    try std.testing.expectEqualStrings("id.example.test", result.pending.user_domain);
    for ([_][]const u8{ "alice", "alice@@example.test", "https://example.test", "alice@example.test:+443" }) |input| {
        try std.testing.expectError(error.InvalidInput, beginLocalLogin(a, .{ .key_material = km, .callback_url = "http://localhost/callback", .user_domain = input, .now = now, .dns = failing.resolver() }));
    }
}

test "beginLocalLogin retains caller-supplied required claims in the pending state" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try testKeyMaterial(a, now);
    var failing = FakeDnsResolver.failing();

    const custom_required = [_][]const u8{ "email", "handle" };
    const result = try beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "http://localhost/callback",
        .user_domain = "example.com",
        .required_claims = &custom_required,
        .now = now,
        .dns = failing.resolver(),
    });

    try std.testing.expectEqual(@as(usize, 2), result.pending.required_claims.len);
    try std.testing.expectEqualStrings("email", result.pending.required_claims[0]);
    try std.testing.expectEqualStrings("handle", result.pending.required_claims[1]);
}

test "PendingLogin.required_claims round-trips through JSON (the app's own serialize form)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const now: i64 = try local_rp.parseTimestamp("2026-01-01T00:00:00Z");
    const km = try testKeyMaterial(a, now);
    var failing = FakeDnsResolver.failing();

    const custom_required = [_][]const u8{ "email", "handle" };
    const result = try beginLocalLogin(a, .{
        .key_material = km,
        .callback_url = "http://localhost/callback",
        .user_domain = "example.com",
        .required_claims = &custom_required,
        .now = now,
        .dns = failing.resolver(),
    });

    const json_bytes = try std.json.stringifyAlloc(a, result.pending, .{});
    const parsed = try std.json.parseFromSlice(PendingLogin, a, json_bytes, .{});
    defer parsed.deinit();

    try std.testing.expectEqual(@as(usize, 2), parsed.value.required_claims.len);
    try std.testing.expectEqualStrings("email", parsed.value.required_claims[0]);
    try std.testing.expectEqualStrings("handle", parsed.value.required_claims[1]);
    try std.testing.expectEqualStrings(result.pending.user_domain, parsed.value.user_domain);
}

// ---------------------------------------------------------------------
// Browser endpoint discovery (parity with sdks/local-rp/go/browser_test.go)
// ---------------------------------------------------------------------

// Case 1: a valid https= host is used for the redirect instead of the
// identity domain. Case 8: PendingLogin.user_domain stays the identity
// domain — verification stays bound to it, not to the service host.
test "beginLocalLogin uses the discovered https host" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var fake = FakeDnsResolver{ .apis_txts = &.{"v=lk1 tcp=linkkeys.ident.example.test https=linkkeys.ident.example.test"} };
    const result = try beginWith(a, &fake);
    try std.testing.expect(std.mem.startsWith(u8, result.redirect.redirect_url, "https://linkkeys.ident.example.test/auth/local-rp?signed_request="));
    try std.testing.expect(!std.mem.startsWith(u8, result.redirect.redirect_url, "https://" ++ test_domain ++ "/"));
    try std.testing.expectEqualStrings(test_domain, result.pending.user_domain);
}

// Case 2: an https= value with a path prefix preserves that prefix.
test "beginLocalLogin preserves an https= path prefix" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var fake = FakeDnsResolver{ .apis_txts = &.{"v=lk1 https=login.example.test/linkkeys"} };
    const result = try beginWith(a, &fake);
    try std.testing.expect(std.mem.startsWith(u8, result.redirect.redirect_url, "https://login.example.test/linkkeys/auth/local-rp?signed_request="));
}

// Case 3: a record with only tcp= falls back to the identity domain.
test "beginLocalLogin falls back to the identity domain on a tcp-only record" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var fake = FakeDnsResolver{ .apis_txts = &.{"v=lk1 tcp=linkkeys.ident.example.test"} };
    const result = try beginWith(a, &fake);
    try std.testing.expect(std.mem.startsWith(u8, result.redirect.redirect_url, "https://" ++ test_domain ++ "/auth/local-rp?signed_request="));
}

// Case 4: a DNS lookup error falls back to the identity domain.
test "beginLocalLogin falls back to the identity domain on a DNS error" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var failing = FakeDnsResolver.failing();
    const result = try beginWith(a, &failing);
    try std.testing.expect(std.mem.startsWith(u8, result.redirect.redirect_url, "https://" ++ test_domain ++ "/auth/local-rp?signed_request="));
}

// Cases 5 + 6: invalid TXT records are ignored, and across several records
// the FIRST valid record with https= is selected.
test "beginLocalLogin selects the first valid https= record across records" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var fake = FakeDnsResolver{ .apis_txts = &.{
        "not a linkkeys record",
        "v=lk2 https=wrong-version.example.test",
        "v=lk1 tcp=tcp-only.example.test",
        "v=lk1 https=first.example.test",
        "v=lk1 https=second.example.test",
    } };
    const result = try beginWith(a, &fake);
    try std.testing.expect(std.mem.startsWith(u8, result.redirect.redirect_url, "https://first.example.test/auth/local-rp?signed_request="));
}

// Case 7: signed_request rides the discovered URL unchanged — it decodes to
// the signed login request whose fields match this login.
test "beginLocalLogin signed_request survives the discovered URL" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var fake = FakeDnsResolver{ .apis_txts = &.{"v=lk1 https=login.example.test/linkkeys"} };
    const result = try beginWith(a, &fake);

    const uri = try std.Uri.parse(result.redirect.redirect_url);
    const query = switch (uri.query.?) {
        .raw, .percent_encoded => |s| s,
    };
    try std.testing.expect(std.mem.startsWith(u8, query, "signed_request="));
    const param = query["signed_request=".len..];
    try std.testing.expect(std.mem.indexOfScalar(u8, param, '&') == null);

    const signed = try encoding.signedLocalRpLoginRequestFromUrlParam(a, param);
    const request = try @import("types.zig").decodeLocalRpLoginRequest(a, signed.request);
    try std.testing.expectEqualStrings("http://app.lan:8080/cb", request.callback_url);
    try std.testing.expectEqualSlices(u8, result.pending.nonce, request.nonce);
}

// Case 9: a config literal that omits `dns` compiles unchanged and defaults
// to the system resolver. The default path is not executed here — that
// would be a live DNS request.
test "BeginLocalLoginConfig without a resolver still compiles" {
    const config = BeginLocalLoginConfig{
        .key_material = undefined,
        .callback_url = "http://app.lan:8080/cb",
        .user_domain = test_domain,
        .now = 0,
    };
    try std.testing.expect(config.dns == null);
}
