apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demoappsite.fullname" . }}
  labels:
    {{- include "demoappsite.labels" . | nindent 4 }}
type: Opaque
data:
  ROCKET_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- if .Values.rp.apiKey }}
  RP_API_KEY: {{ .Values.rp.apiKey | b64enc | quote }}
  {{- end }}
